version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    depends_on:
      - database
    env_file:
      - ./api/.env
  databse:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=globantchallenge
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-inidb.d/
volumes:
  postgres_data:

